services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: coderank-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: coderank-kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: coderank-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://coderank-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mysql:
    image: mysql:8.0
    container_name: coderank-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: executor
      MYSQL_USER: coderank
      MYSQL_PASSWORD: coderank
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    container_name: coderank-api
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DATABASE_URL: mysql+pymysql://coderank:coderank@mysql:3306/executor
      KAFKA_BOOTSTRAP_SERVERS: coderank-kafka:9092

  worker:
    build: .
    container_name: coderank-worker
    command: python -u -m app.consumer
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      runner-python:
        condition: service_started
      runner-node:
        condition: service_started
      runner-cpp:
        condition: service_started
      runner-java:
        condition: service_started
    environment:
      DATABASE_URL: mysql+pymysql://coderank:coderank@mysql:3306/executor
      KAFKA_BOOTSTRAP_SERVERS: coderank-kafka:9092
      HOST_CODE_DIR: /Users/agamyamehrotra/Desktop/coderank-kafka
      RUNNER_BASE_DIR: /code/runner
    volumes:
    - /Users/agamyamehrotra/Desktop/coderank-kafka:/code
    - /var/run/docker.sock:/var/run/docker.sock


  runner-python:
    build:
      context: ./runners/python
    image: coderank-python

  runner-node:
    build:
      context: ./runners/node
    image: coderank-node

  runner-cpp:
    build:
      context: ./runners/cpp
    image: coderank-cpp

  runner-java:
    build:
      context: ./runners/java
    image: coderank-java

volumes:
  mysql_data:
